services:
  profile:
    build:
      context: ./packages/services/profile
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3001:3001"


  cart:
    build:
      context: ./packages/services/cart
    environment:
      - PORT=3002
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3002:3002"


  notifications:
    build:
      context: ./packages/services/notifications
    environment:
      - PORT=3003
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3003:3003"


  wishlist:
    build:
      context: ./packages/services/wishlist
    environment:
      - PORT=3004
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3004:3004"


  orders:
    build:
      context: ./packages/services/orders
    environment:
      - PORT=3005
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3005:3005"


  payments:
    build:
      context: ./packages/services/payments
    environment:
      - PORT=3006
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3006:3006"


  helpcenter:
    build:
      context: ./packages/services/helpcenter
    environment:
      - PORT=3007
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3007:3007"


  address:
    build:
      context: ./packages/services/address
    environment:
      - PORT=3008
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3008:3008"


  reviews:
    build:
      context: ./packages/services/reviews
    environment:
      - PORT=3009
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3009:3009"


  auth:
    build:
      context: ./packages/services/auth
    environment:
      - PORT=3010
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
      
    ports:
      - "3010:3010"



