services:
  profile:
    build:
      context: ./packages/services/profile
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  cart:
    build:
      context: ./packages/services/cart
    environment:
      - PORT=3002
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3002:3002"
    depends_on:
      - mysql

  notifications:
    build:
      context: ./packages/services/notifications
    environment:
      - PORT=3003
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3003:3003"
    depends_on:
      - mysql

  wishlist:
    build:
      context: ./packages/services/wishlist
    environment:
      - PORT=3004
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3004:3004"
    depends_on:
      - mysql

  orders:
    build:
      context: ./packages/services/orders
    environment:
      - PORT=3005
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3005:3005"
    depends_on:
      - mysql

  payments:
    build:
      context: ./packages/services/payments
    environment:
      - PORT=3006
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3006:3006"
    depends_on:
      - mysql

  helpcenter:
    build:
      context: ./packages/services/helpcenter
    environment:
      - PORT=3007
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3007:3007"
    depends_on:
      - mysql

  address:
    build:
      context: ./packages/services/address
    environment:
      - PORT=3008
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3008:3008"
    depends_on:
      - mysql

  reviews:
    build:
      context: ./packages/services/reviews
    environment:
      - PORT=3009
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
    ports:
      - "3009:3009"
    depends_on:
      - mysql

  auth:
    build:
      context: ./packages/services/auth
    environment:
      - PORT=3010
      - DATABASE_URL=mysql://admin:Devops123@ecommerce.chgqk6us4gk8.ap-south-1.rds.amazonaws.com:3306/mysql
      
    ports:
      - "3010:3010"
    depends_on:
      - mysql


