apiVersion: v1
kind: Secret
metadata:
  name: secret-db
type: Opaque
data:
  DATABASE_URL: bXlzcWw6Ly9hZG1pbjpEZXZvcHMxMjNAbXlzcWwuY2hncWs2dXM0Z2s4LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi9teXNxbA==