apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: sap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels: 
        app: notifications
    spec:
      containers:
        - image: shahir5890/backend_notifications:7
          name:  notifications
          ports:
          - containerPort: 3003
          env:
          - name:  PORT
            value:  "3003"
          - name:  DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: DATABASE_URL
---
kind: Service
apiVersion: v1
metadata:
  name:  notifications
  namespace: sap
spec:
  selector:
    app:  notifications
  type:  ClusterIP
  ports:
  - port:  3003
    targetPort:  3003