apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wishlist
  namespace: sap
spec:
  selector:
    matchLabels:
      app: wishlist
  replicas: 1
  template:
    metadata:
      labels:
        app:  wishlist
    spec:
      containers:
      - name:  wishlist
        image: shahir5890/backend_wishlist:12
        env:
        - name: PORT
          value: "3004"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: DATABASE_URL
        ports:
        - containerPort:  3004
---
apiVersion: v1
kind: Service
metadata:
  name:  wishlist
  namespace: sap
spec:
  selector:
    app:  wishlist
  type:  ClusterIP
  ports:
  - port:  3004
    targetPort:  3004