apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: sap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: shahir5890/backend_auth:12
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: "3010"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: sap
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - port: 3010
    targetPort: 3010
